# Generated by Django 5.2.4 on 2025-07-06 01:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="fecha_registro",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
