# Generated by Django 5.2.4 on 2025-07-06 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0002_alter_usuario_fecha_registro"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="materia",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="grades.materia",
            ),
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.IntegerField(
                        choices=[
                            (1, "PRIMERO"),
                            (2, "SEGUNDO"),
                            (3, "TERCERO"),
                            (4, "CUARTO"),
                            (5, "QUINTO"),
                            (6, "SEXTO"),
                            (7, "SEPTIMO"),
                            (8, "OCTAVO"),
                            (9, "NOVENO"),
                            (10, "DECIMO"),
                            (11, "ONCE"),
                        ]
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grades.profesor",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="grado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="grades.curso"
            ),
        ),
    ]
