# Generated by Django 5.2.4 on 2025-07-06 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0003_nota_materia_curso_alter_estudiante_grado"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="estudiante",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grades.estudiante",
            ),
        ),
    ]
