# Generated by Django 5.2.4 on 2025-07-06 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0004_nota_estudiante"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fechaEntrada", models.DateField()),
                ("fechaSalida", models.DateField()),
                (
                    "profesor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="grades.profesor",
                    ),
                ),
            ],
        ),
    ]
