# Generated by Django 5.2.4 on 2025-07-07 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0005_regisasistencia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profesor",
            name="fecha_ingreso",
        ),
        migrations.RemoveField(
            model_name="profesor",
            name="fecha_salida",
        ),
        migrations.AddField(
            model_name="estudiante",
            name="cursos",
            field=models.ManyToManyField(related_name="estudiantes", to="grades.curso"),
        ),
        migrations.AlterField(
            model_name="estudiante",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profesor",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
