# Generated by Django 5.2.4 on 2025-07-07 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0006_remove_profesor_fecha_ingreso_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materia",
            name="estudiante",
        ),
        migrations.RemoveField(
            model_name="materia",
            name="profesor",
        ),
        migrations.AddField(
            model_name="materia",
            name="curso",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grades.curso",
            ),
        ),
    ]
