# Generated by Django 5.2.4 on 2025-07-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0007_remove_materia_estudiante_remove_materia_profesor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="materia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grades.materia",
            ),
        ),
    ]
