# Generated by Django 5.2.4 on 2025-07-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0008_alter_nota_materia"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="nombre",
            field=models.CharField(default="Sin nombre", max_length=200),
        ),
    ]
