# Generated by Django 5.2.4 on 2025-07-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0009_nota_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="nota",
            name="porcentaje",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="nota",
            name="valor",
            field=models.IntegerField(default=0),
        ),
    ]
