# Generated by Django 5.2.4 on 2025-07-07 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0010_nota_porcentaje_alter_nota_valor"),
    ]

    operations = [
        migrations.AddField(
            model_name="materia",
            name="profesor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grades.profesor",
            ),
        ),
    ]
