# Generated by Django 5.2.4 on 2025-07-07 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0011_materia_profesor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profesor",
            name="especialidad",
        ),
    ]
