# Generated by Django 5.2.4 on 2025-07-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0012_remove_profesor_especialidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="profesor",
            name="especialidad",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
