# Generated by Django 5.2.4 on 2025-07-08 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0013_profesor_especialidad"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(default="Sin nombre", max_length=200)),
                ("porcentaje", models.FloatField(default=0)),
                ("comentario", models.CharField(max_length=100)),
                ("periodo_academico", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="nota",
            name="actividad",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notas",
                to="grades.actividad",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="nota",
            unique_together={("actividad", "estudiante")},
        ),
        migrations.RemoveField(
            model_name="nota",
            name="comentario",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="periodo_academico",
        ),
        migrations.RemoveField(
            model_name="nota",
            name="porcentaje",
        ),
    ]
