# Generated by Django 5.2.4 on 2025-07-08 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0014_actividad_nota_actividad_alter_nota_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividad",
            name="materia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="grades.materia",
            ),
        ),
    ]
