# Generated by Django 5.2.4 on 2025-07-08 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0016_alter_actividad_materia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividad",
            name="materia",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades",
                to="grades.materia",
            ),
        ),
    ]
