# Generated by Django 5.2.4 on 2025-07-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grades", "0017_alter_actividad_materia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actividad",
            name="comentario",
            field=models.CharField(default="Pendiente", max_length=100),
        ),
    ]
